blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/dlq/pannes-historiques/security/advisories/new
    about: Please report security concerns privately.
